// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryjiceforuazsjahtqwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5amljZWZvcnVhenNqYWh0cXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDc5NzIsImV4cCI6MjA1OTIyMzk3Mn0.YOBxWHMtFdPIyd5e51z9ad8e60vIUO6P3eQ9Ed1tsOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);